# Generated by Django 2.2 on 2019-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_stm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='garage',
            name='account_type',
            field=models.CharField(default='GARAGE', max_length=144),
        ),
    ]
