# Generated by Django 2.2 on 2019-08-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_stm'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='registration_number',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
