# Generated by Django 2.2 on 2019-08-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_stm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='closing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='garage',
            name='commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='garage',
            name='commission_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='garage',
            name='earnings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='garage',
            name='opening_time',
            field=models.TimeField(null=True),
        ),
    ]
