# Generated by Django 2.2 on 2019-08-25 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_stm'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='actions',
            field=models.CharField(default=datetime.datetime(2019, 8, 25, 10, 59, 1, 113681, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='car_model',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='customer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='average_quadrant_premium',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_subtype',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='curb_weight',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='def_engine_aspiration',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='def_engine_block',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='def_engine_cylinders',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='def_engine_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='def_engine_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='def_trans_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='def_trans_speeds',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='def_trans_type',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='doors',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_size_uom',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ext_b_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ext_color_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ext_g_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ext_mfr_color_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ext_mfr_color_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ext_r_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gross_vehicle_weight_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gvw_range',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='int_b_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='int_color_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='int_g_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='int_mfr_color_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='int_mfr_color_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='int_r_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_primary',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='max_payload',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='msrp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plant',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='restraint_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='style',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tmp_tank1_gal',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tmp_wheel_dia',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='wheelbase',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.SmallIntegerField(db_index=True, null=True),
        ),
    ]
