# Generated by Django 2.2 on 2019-08-25 13:22

from django.db import migrations, models
import django.db.models.deletion
import garage.enums


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_stm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='car_model',
        ),
        migrations.AddField(
            model_name='job',
            name='mechanic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[(garage.enums.JobStatus('INCOMING'), 'INCOMING'), (garage.enums.JobStatus('ACCEPTED'), 'ACCEPTED'), (garage.enums.JobStatus('STARTED'), 'STARTED'), (garage.enums.JobStatus('COMPLETED'), 'COMPLETED')], default=garage.enums.JobStatus('INCOMING'), max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='garage.Vehicle'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=144)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='garage.Job')),
            ],
        ),
    ]
