# Generated by Django 2.2 on 2019-08-25 11:35

from django.db import migrations, models
import django.db.models.deletion
import garage.enums


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_stm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='car_model',
        ),
        migrations.AddField(
            model_name='job',
            name='mechanic',
            field=models.CharField(default='No Mechanic', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[(garage.enums.JobStatus('INCOMING'), 'INCOMING'), (garage.enums.JobStatus('ACCEPTED'), 'ACCEPTED'), (garage.enums.JobStatus('STARTED'), 'STARTED'), (garage.enums.JobStatus('COMPLETED'), 'COMPLETED')], default=garage.enums.JobStatus('INCOMING'), max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='garage.Vehicle'),
            preserve_default=False,
        ),
    ]
