# Generated by Django 2.2 on 2019-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_stm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='customer_name',
            field=models.CharField(max_length=144),
        ),
        migrations.AlterField(
            model_name='job',
            name='mechanic',
            field=models.CharField(max_length=144, null=True),
        ),
    ]
