# Generated by Django 2.2 on 2019-08-25 13:34

from django.db import migrations, models
import garage.enums


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_stm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[(garage.enums.JobStatus('INCOMING'), 'INCOMING'), (garage.enums.JobStatus('ACCEPTED'), 'ACCEPTED'), (garage.enums.JobStatus('STARTED'), 'STARTED'), (garage.enums.JobStatus('COMPLETED'), 'COMPLETED')], default=garage.enums.JobStatus('INCOMING'), max_length=50),
        ),
    ]
