# Generated by Django 2.2 on 2019-08-25 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import garage.enums


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_stm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0)),
                ('status', models.CharField(choices=[(garage.enums.QuoteStatus('OPEN'), 'OPEN'), (garage.enums.QuoteStatus('EXPIRED'), 'EXPIRED'), (garage.enums.QuoteStatus('CLOSED'), 'CLOSED')], default=garage.enums.QuoteStatus('OPEN'), max_length=100)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quotes', to='garage.Job')),
            ],
        ),
    ]
