# Generated by Django 2.2 on 2019-08-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0012_stm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0)),
                ('description', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=300)),
                ('payee', models.CharField(max_length=300)),
                ('transaction_code', models.CharField(max_length=300)),
            ],
        ),
    ]
